package backend

import (
	"context"
	"net/http"
	"strconv"
	"strings"

	"github.com/danielgtaylor/huma/v2"
	"github.com/swaggest/swgui/v5emb"
)

type healthResponse struct {
	Body map[string]string
}

type routeDoc struct {
	Method      string
	Path        string
	Tags        []string
	Summary     string
	Public      bool
	RequestBody bool
	Multipart   bool
	Status      int
}

func openAPIConfig() huma.Config {
	config := huma.DefaultConfig("Rayboard API", "0.1.0")
	config.OpenAPIPath = "/api/openapi"
	config.DocsPath = ""
	config.SchemasPath = ""
	config.OpenAPI.Servers = []*huma.Server{{URL: "/"}}
	config.OpenAPI.Components.SecuritySchemes = map[string]*huma.SecurityScheme{
		"bearerToken": {
			Type:         "http",
			Scheme:       "bearer",
			BearerFormat: "Rayboard API token",
			Description:  "API token generated by an authenticated user.",
		},
		"sessionCookie": {
			Type:        "apiKey",
			In:          "cookie",
			Name:        "rayboard_session",
			Description: "Browser session cookie created by POST /api/login.",
		},
		"csrfToken": {
			Type:        "apiKey",
			In:          "header",
			Name:        "X-CSRF-Token",
			Description: "Required for mutating requests authenticated with a browser session cookie.",
		},
	}
	config.OpenAPI.Security = []map[string][]string{
		{"bearerToken": {}},
		{"sessionCookie": {}},
	}
	return config
}

func registerOpenAPIRoutes(api huma.API) {
	huma.Register(api, huma.Operation{
		OperationID: "health",
		Method:      http.MethodGet,
		Path:        "/api/health",
		Summary:     "Backend health check",
		Tags:        []string{"System"},
		Security:    []map[string][]string{},
		Responses: map[string]*huma.Response{
			"200": jsonResponse("Backend health status", objectSchema(map[string]*huma.Schema{
				"status":  {Type: "string"},
				"service": {Type: "string"},
			}, "status", "service")),
		},
	}, func(context.Context, *struct{}) (*healthResponse, error) {
		return &healthResponse{Body: map[string]string{
			"status":  "ok",
			"service": "backend",
		}}, nil
	})

	for _, doc := range legacyRouteDocs() {
		api.OpenAPI().AddOperation(routeOperation(doc))
	}
}

func registerAPIDocsRoute(mux *http.ServeMux) {
	handler := v5emb.New("Rayboard API", "/api/openapi.json", "/api/docs")
	mux.Handle("GET /api/docs", handler)
	mux.Handle("GET /api/docs/", handler)
}

func routeOperation(doc routeDoc) *huma.Operation {
	status := doc.Status
	if status == 0 {
		status = http.StatusOK
	}

	op := &huma.Operation{
		OperationID: operationID(doc.Method, doc.Path),
		Method:      doc.Method,
		Path:        doc.Path,
		Tags:        doc.Tags,
		Summary:     doc.Summary,
		Parameters:  pathParams(doc.Path),
		Responses: map[string]*huma.Response{
			statusCode(status): responseForStatus(status),
			"default":          errorResponse(),
		},
	}
	if doc.Public {
		op.Security = []map[string][]string{}
	}
	if doc.RequestBody {
		mediaType := "application/json"
		schema := genericObjectSchema()
		if doc.Multipart {
			mediaType = "multipart/form-data"
			schema = objectSchema(map[string]*huma.Schema{
				"file": {Type: "string", Format: "binary"},
			}, "file")
		}
		op.RequestBody = &huma.RequestBody{
			Required: true,
			Content: map[string]*huma.MediaType{
				mediaType: {Schema: schema},
			},
		}
	}
	return op
}

func jsonResponse(description string, schema *huma.Schema) *huma.Response {
	return &huma.Response{
		Description: description,
		Content: map[string]*huma.MediaType{
			"application/json": {Schema: schema},
		},
	}
}

func responseForStatus(status int) *huma.Response {
	if status == http.StatusNoContent {
		return &huma.Response{Description: http.StatusText(status)}
	}
	return jsonResponse(http.StatusText(status), genericObjectSchema())
}

func errorResponse() *huma.Response {
	return jsonResponse("Rayboard error response", objectSchema(map[string]*huma.Schema{
		"error": objectSchema(map[string]*huma.Schema{
			"code":    {Type: "string"},
			"message": {Type: "string"},
			"fields":  {Type: "object", AdditionalProperties: &huma.Schema{Type: "string"}},
		}, "code", "message"),
	}, "error"))
}

func genericObjectSchema() *huma.Schema {
	return &huma.Schema{Type: "object", AdditionalProperties: true}
}

func objectSchema(properties map[string]*huma.Schema, required ...string) *huma.Schema {
	return &huma.Schema{Type: "object", Properties: properties, Required: required}
}

func pathParams(path string) []*huma.Param {
	parts := strings.Split(path, "/")
	params := make([]*huma.Param, 0)
	for _, part := range parts {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			name := strings.TrimSuffix(strings.TrimPrefix(part, "{"), "}")
			params = append(params, &huma.Param{
				Name:     name,
				In:       "path",
				Required: true,
				Schema:   &huma.Schema{Type: "string"},
			})
		}
	}
	return params
}

func operationID(method string, path string) string {
	pathID := strings.Trim(path, "/")
	pathID = strings.TrimPrefix(pathID, "api/")
	pathID = strings.ReplaceAll(pathID, "{", "by-")
	pathID = strings.ReplaceAll(pathID, "}", "")
	pathID = strings.ReplaceAll(pathID, "/", "-")
	pathID = strings.ReplaceAll(pathID, "_", "-")
	return strings.ToLower(method) + "-" + pathID
}

func statusCode(status int) string {
	return strconv.Itoa(statusCodeInt(status))
}

func statusCodeInt(status int) int {
	if status == 0 {
		return http.StatusOK
	}
	return status
}

func legacyRouteDocs() []routeDoc {
	return []routeDoc{
		{Method: http.MethodPost, Path: "/api/login", Tags: []string{"Auth"}, Summary: "Log in with username and password", Public: true, RequestBody: true},
		{Method: http.MethodPost, Path: "/api/logout", Tags: []string{"Auth"}, Summary: "Log out current session", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/me", Tags: []string{"Auth"}, Summary: "Get current authenticated user"},
		{Method: http.MethodGet, Path: "/api/tokens", Tags: []string{"Auth"}, Summary: "List API tokens"},
		{Method: http.MethodPost, Path: "/api/tokens", Tags: []string{"Auth"}, Summary: "Create API token", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodDelete, Path: "/api/tokens/{token_id}", Tags: []string{"Auth"}, Summary: "Revoke API token", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/users", Tags: []string{"Users"}, Summary: "List users"},
		{Method: http.MethodPost, Path: "/api/users", Tags: []string{"Users"}, Summary: "Create user", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/users/{user_id}", Tags: []string{"Users"}, Summary: "Get user"},
		{Method: http.MethodPatch, Path: "/api/users/{user_id}", Tags: []string{"Users"}, Summary: "Update user", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/users/{user_id}", Tags: []string{"Users"}, Summary: "Delete user", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/groups", Tags: []string{"RBAC"}, Summary: "List groups"},
		{Method: http.MethodPost, Path: "/api/groups", Tags: []string{"RBAC"}, Summary: "Create group", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/groups/{group_id}/members", Tags: []string{"RBAC"}, Summary: "List group members"},
		{Method: http.MethodPost, Path: "/api/groups/{group_id}/members/{user_id}", Tags: []string{"RBAC"}, Summary: "Add group member"},
		{Method: http.MethodDelete, Path: "/api/groups/{group_id}/members/{user_id}", Tags: []string{"RBAC"}, Summary: "Remove group member", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/roles", Tags: []string{"RBAC"}, Summary: "List roles"},
		{Method: http.MethodGet, Path: "/api/role-bindings", Tags: []string{"RBAC"}, Summary: "List role bindings"},
		{Method: http.MethodPost, Path: "/api/role-bindings", Tags: []string{"RBAC"}, Summary: "Create role binding", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodDelete, Path: "/api/role-bindings/{binding_id}", Tags: []string{"RBAC"}, Summary: "Delete role binding", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/projects", Tags: []string{"Projects"}, Summary: "List projects"},
		{Method: http.MethodPost, Path: "/api/projects", Tags: []string{"Projects"}, Summary: "Create project", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}", Tags: []string{"Projects"}, Summary: "Get project"},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/backlog", Tags: []string{"Backlog"}, Summary: "List project backlog"},
		{Method: http.MethodPatch, Path: "/api/projects/{project_id}/backlog", Tags: []string{"Backlog"}, Summary: "Reorder project backlog", RequestBody: true},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/components", Tags: []string{"Components"}, Summary: "List project components"},
		{Method: http.MethodPost, Path: "/api/projects/{project_id}/components", Tags: []string{"Components"}, Summary: "Create project component", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/versions", Tags: []string{"Versions"}, Summary: "List project versions"},
		{Method: http.MethodPost, Path: "/api/projects/{project_id}/versions", Tags: []string{"Versions"}, Summary: "Create project version", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/custom-fields", Tags: []string{"Custom Fields"}, Summary: "List project custom fields"},
		{Method: http.MethodPost, Path: "/api/projects/{project_id}/custom-fields", Tags: []string{"Custom Fields"}, Summary: "Create project custom field", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/tickets", Tags: []string{"Tickets"}, Summary: "List project tickets"},
		{Method: http.MethodPost, Path: "/api/projects/{project_id}/tickets", Tags: []string{"Tickets"}, Summary: "Create ticket", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/roadmap", Tags: []string{"Roadmap"}, Summary: "List project roadmap epics with progress"},
		{Method: http.MethodGet, Path: "/api/tickets/{ticket_id}", Tags: []string{"Tickets"}, Summary: "Get ticket"},
		{Method: http.MethodPatch, Path: "/api/tickets/{ticket_id}", Tags: []string{"Tickets"}, Summary: "Update ticket", RequestBody: true},
		{Method: http.MethodGet, Path: "/api/tickets/{ticket_id}/activity", Tags: []string{"Tickets"}, Summary: "List ticket activity"},
		{Method: http.MethodGet, Path: "/api/tickets/{ticket_id}/comments", Tags: []string{"Comments"}, Summary: "List ticket comments"},
		{Method: http.MethodPost, Path: "/api/tickets/{ticket_id}/comments", Tags: []string{"Comments"}, Summary: "Create ticket comment", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodDelete, Path: "/api/comments/{comment_id}", Tags: []string{"Comments"}, Summary: "Delete comment", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/tickets/{ticket_id}/attachments", Tags: []string{"Attachments"}, Summary: "List ticket attachments"},
		{Method: http.MethodPost, Path: "/api/tickets/{ticket_id}/attachments", Tags: []string{"Attachments"}, Summary: "Upload ticket attachment", RequestBody: true, Multipart: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/attachments/{attachment_id}/download", Tags: []string{"Attachments"}, Summary: "Download attachment"},
		{Method: http.MethodDelete, Path: "/api/attachments/{attachment_id}", Tags: []string{"Attachments"}, Summary: "Delete attachment", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/projects/{project_id}/sprints", Tags: []string{"Sprints"}, Summary: "List project sprints"},
		{Method: http.MethodPost, Path: "/api/projects/{project_id}/sprints", Tags: []string{"Sprints"}, Summary: "Create sprint", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/sprints/{sprint_id}", Tags: []string{"Sprints"}, Summary: "Get sprint"},
		{Method: http.MethodPatch, Path: "/api/sprints/{sprint_id}", Tags: []string{"Sprints"}, Summary: "Update sprint", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/sprints/{sprint_id}", Tags: []string{"Sprints"}, Summary: "Delete sprint", Status: http.StatusNoContent},
		{Method: http.MethodPost, Path: "/api/sprints/{sprint_id}/start", Tags: []string{"Sprints"}, Summary: "Start sprint"},
		{Method: http.MethodPost, Path: "/api/sprints/{sprint_id}/complete", Tags: []string{"Sprints"}, Summary: "Complete sprint", RequestBody: true},
		{Method: http.MethodPut, Path: "/api/tickets/{ticket_id}/sprint", Tags: []string{"Sprints"}, Summary: "Assign ticket to sprint", RequestBody: true},
		{Method: http.MethodPatch, Path: "/api/tickets/{ticket_id}/sprint", Tags: []string{"Sprints"}, Summary: "Assign ticket to sprint", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/tickets/{ticket_id}/sprint", Tags: []string{"Sprints"}, Summary: "Remove ticket from sprint", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/components/{component_id}", Tags: []string{"Components"}, Summary: "Get component"},
		{Method: http.MethodPatch, Path: "/api/components/{component_id}", Tags: []string{"Components"}, Summary: "Update component", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/components/{component_id}", Tags: []string{"Components"}, Summary: "Delete component", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/versions/{version_id}", Tags: []string{"Versions"}, Summary: "Get version"},
		{Method: http.MethodPatch, Path: "/api/versions/{version_id}", Tags: []string{"Versions"}, Summary: "Update version", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/versions/{version_id}", Tags: []string{"Versions"}, Summary: "Delete version", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/custom-fields/{field_id}", Tags: []string{"Custom Fields"}, Summary: "Get custom field"},
		{Method: http.MethodPatch, Path: "/api/custom-fields/{field_id}", Tags: []string{"Custom Fields"}, Summary: "Update custom field", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/custom-fields/{field_id}", Tags: []string{"Custom Fields"}, Summary: "Delete custom field", Status: http.StatusNoContent},
		{Method: http.MethodPost, Path: "/api/search", Tags: []string{"Search"}, Summary: "Search tickets with CEL query", RequestBody: true},
		{Method: http.MethodGet, Path: "/api/saved-views", Tags: []string{"Saved Views"}, Summary: "List saved views"},
		{Method: http.MethodPost, Path: "/api/saved-views", Tags: []string{"Saved Views"}, Summary: "Create saved view", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/saved-views/{view_id}", Tags: []string{"Saved Views"}, Summary: "Get saved view"},
		{Method: http.MethodPatch, Path: "/api/saved-views/{view_id}", Tags: []string{"Saved Views"}, Summary: "Update saved view", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/saved-views/{view_id}", Tags: []string{"Saved Views"}, Summary: "Delete saved view", Status: http.StatusNoContent},
		{Method: http.MethodGet, Path: "/api/cron-jobs", Tags: []string{"Cron Jobs"}, Summary: "List cron jobs"},
		{Method: http.MethodPost, Path: "/api/cron-jobs", Tags: []string{"Cron Jobs"}, Summary: "Create cron job", RequestBody: true, Status: http.StatusCreated},
		{Method: http.MethodGet, Path: "/api/cron-jobs/{job_id}", Tags: []string{"Cron Jobs"}, Summary: "Get cron job"},
		{Method: http.MethodPatch, Path: "/api/cron-jobs/{job_id}", Tags: []string{"Cron Jobs"}, Summary: "Update cron job", RequestBody: true},
		{Method: http.MethodDelete, Path: "/api/cron-jobs/{job_id}", Tags: []string{"Cron Jobs"}, Summary: "Delete cron job", Status: http.StatusNoContent},
		{Method: http.MethodPost, Path: "/api/cron-jobs/{job_id}/run", Tags: []string{"Cron Jobs"}, Summary: "Run cron job now"},
		{Method: http.MethodGet, Path: "/api/cron-jobs/{job_id}/runs", Tags: []string{"Cron Jobs"}, Summary: "List cron job runs"},
		{Method: http.MethodGet, Path: "/api/notifications", Tags: []string{"Notifications"}, Summary: "List notifications"},
		{Method: http.MethodPost, Path: "/api/notifications/read-all", Tags: []string{"Notifications"}, Summary: "Mark all notifications read"},
		{Method: http.MethodPost, Path: "/api/notifications/{notification_id}/read", Tags: []string{"Notifications"}, Summary: "Mark notification read"},
		{Method: http.MethodPost, Path: "/api/notifications/{notification_id}/unread", Tags: []string{"Notifications"}, Summary: "Mark notification unread"},
	}
}
