package httpapi

import (
	"context"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humago"
	redoc "github.com/mvrilo/go-redoc"
	"github.com/swaggest/swgui/v5emb"
	"github.com/timo-42/rayboard/internal/backend/attachments"
	"github.com/timo-42/rayboard/internal/backend/audit"
	"github.com/timo-42/rayboard/internal/backend/auth"
	"github.com/timo-42/rayboard/internal/backend/authz"
	"github.com/timo-42/rayboard/internal/backend/comments"
	"github.com/timo-42/rayboard/internal/backend/cronjobs"
	attachmentapi "github.com/timo-42/rayboard/internal/backend/httpapi/attachments"
	"github.com/timo-42/rayboard/internal/backend/httpapi/authapi"
	"github.com/timo-42/rayboard/internal/backend/httpapi/boards"
	commentapi "github.com/timo-42/rayboard/internal/backend/httpapi/comments"
	"github.com/timo-42/rayboard/internal/backend/httpapi/components"
	"github.com/timo-42/rayboard/internal/backend/httpapi/cronapi"
	"github.com/timo-42/rayboard/internal/backend/httpapi/customfields"
	"github.com/timo-42/rayboard/internal/backend/httpapi/notificationsapi"
	"github.com/timo-42/rayboard/internal/backend/httpapi/openrouterapi"
	"github.com/timo-42/rayboard/internal/backend/httpapi/projects"
	"github.com/timo-42/rayboard/internal/backend/httpapi/searchapi"
	"github.com/timo-42/rayboard/internal/backend/httpapi/shared"
	"github.com/timo-42/rayboard/internal/backend/httpapi/sprints"
	"github.com/timo-42/rayboard/internal/backend/httpapi/tickets"
	"github.com/timo-42/rayboard/internal/backend/httpapi/versions"
	"github.com/timo-42/rayboard/internal/backend/notifications"
	"github.com/timo-42/rayboard/internal/backend/openrouter"
	"github.com/timo-42/rayboard/internal/backend/search"
	"github.com/timo-42/rayboard/internal/backend/tracker"
)

type Options struct {
	Auth          *auth.Service
	Audit         *audit.Store
	Authorizer    authz.Evaluator
	Tracker       *tracker.Service
	Attachments   *attachments.Service
	Comments      *comments.Service
	Cron          *cronjobs.Service
	Notifications *notifications.Service
	OpenRouter    *openrouter.Service
	Search        *search.Service
}

type healthResponse struct {
	Body healthResource
}

type healthMetadata struct {
	ID string `json:"id"`
}

type healthSpec struct {
	Service string `json:"service"`
}

type healthStatus struct {
	State string `json:"state"`
}

type healthResource = shared.Resource[healthMetadata, healthSpec, healthStatus]

func NewHandler(options Options) http.Handler {
	mux := http.NewServeMux()
	api := humago.New(mux, openAPIConfig())
	registerHealth(api)
	registerDocs(mux)

	authenticator := shared.Authenticator{Auth: options.Auth, Authorizer: options.Authorizer}
	authapi.Register(api, authapi.Provider{Auth: options.Auth, Audit: options.Audit, Authenticator: authenticator})
	projects.Register(api, projects.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	tickets.Register(api, tickets.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	boards.Register(api, boards.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	sprints.Register(api, sprints.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	components.Register(api, components.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	versions.Register(api, versions.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	customfields.Register(api, customfields.Provider{Tracker: options.Tracker, Authenticator: authenticator})
	commentapi.Register(api, commentapi.Provider{Comments: options.Comments, Authenticator: authenticator})
	attachmentapi.Register(api, attachmentapi.Provider{Attachments: options.Attachments, Authenticator: authenticator})
	searchapi.Register(api, searchapi.Provider{Search: options.Search, Authenticator: authenticator})
	cronapi.Register(api, cronapi.Provider{Cron: options.Cron, Authenticator: authenticator})
	notificationsapi.Register(api, notificationsapi.Provider{Notifications: options.Notifications, Authenticator: authenticator})
	openrouterapi.Register(api, openrouterapi.Provider{OpenRouter: options.OpenRouter, Audit: options.Audit, Authenticator: authenticator})
	return mux
}

func openAPIConfig() huma.Config {
	config := huma.DefaultConfig("Rayboard API", "0.1.0")
	config.OpenAPIPath = "/api/openapi"
	config.DocsPath = ""
	config.SchemasPath = ""
	config.OpenAPI.Servers = []*huma.Server{{URL: "/"}}
	config.OpenAPI.Components.SecuritySchemes = map[string]*huma.SecurityScheme{
		"bearerToken": {
			Type:         "http",
			Scheme:       "bearer",
			BearerFormat: "Rayboard API token",
			Description:  "API token generated by an authenticated user.",
		},
		"sessionCookie": {
			Type:        "apiKey",
			In:          "cookie",
			Name:        "rayboard_session",
			Description: "Browser session cookie created by POST /api/login.",
		},
		"csrfToken": {
			Type:        "apiKey",
			In:          "header",
			Name:        "X-CSRF-Token",
			Description: "Required for mutating requests authenticated with a browser session cookie.",
		},
	}
	config.OpenAPI.Security = []map[string][]string{
		{"bearerToken": {}},
		{"sessionCookie": {}},
	}
	return config
}

func registerHealth(api huma.API) {
	huma.Register(api, huma.Operation{
		OperationID: "health",
		Method:      http.MethodGet,
		Path:        "/api/health",
		Summary:     "Backend health check",
		Tags:        []string{"System"},
		Security:    []map[string][]string{},
	}, func(context.Context, *struct{}) (*healthResponse, error) {
		return &healthResponse{Body: healthResource{
			Metadata: healthMetadata{ID: "backend"},
			Spec:     healthSpec{Service: "backend"},
			Status:   healthStatus{State: "ok"},
		}}, nil
	})
}

func registerDocs(mux *http.ServeMux) {
	handler := v5emb.New("Rayboard API", "/api/openapi.json", "/api/docs")
	mux.Handle("GET /api/docs", handler)
	mux.Handle("GET /api/docs/", handler)

	redocBody, err := redoc.Redoc{
		Title:       "Rayboard API",
		Description: "Rayboard OpenAPI reference",
		SpecPath:    "/api/openapi.json",
	}.Body()
	if err != nil {
		panic(err)
	}
	redocHandler := func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(redocBody)
	}
	mux.HandleFunc("GET /api/docs/redoc", redocHandler)
	mux.HandleFunc("GET /api/docs/redoc/", redocHandler)
}
